const songs = [
  {
    id: 1070615458,
    channelUrl: "https://soundcloud.com/monstercat",
    channelTitle: "Monstercat",
    songUrl: "https://soundcloud.com/monstercat/drinks-on-me-event-horizon-high-caliber",
    songTitle: "Drinks On Me & Event Horizon - High Caliber",
    artworkUrl: "https://i1.sndcdn.com/artworks-tJE2NkFRNVB3xJ39-XtwXCg-t500x500.jpg",
  },
  {
    id: 1030774990,
    channelUrl: "https://soundcloud.com/thearchives_uk",
    channelTitle: "The Archives",
    songUrl: "https://soundcloud.com/thearchives_uk/event-horizon-ptsd",
    songTitle: "Event Horizon - PTSD",
    artworkUrl: "https://i1.sndcdn.com/artworks-jNFK4hinDJuVs6jB-15BMQg-t500x500.jpg",
  },
  {
    id: 991349737,
    channelUrl: "https://soundcloud.com/nightbassrecords",
    channelTitle: "Night Bass",
    songUrl: "https://soundcloud.com/nightbassrecords/event-horizon-swindler",
    songTitle: "Event Horizon - Swindler",
  },
  {
    id: 991351594,
    channelUrl: "https://soundcloud.com/nightbassrecords",
    channelTitle: "Night Bass",
    songUrl: "https://soundcloud.com/nightbassrecords/event-horizon-crutch",
    songTitle: "Event Horizon - Crutch",
  },
  {
    id: 991352830,
    channelUrl: "https://soundcloud.com/nightbassrecords",
    channelTitle: "Night Bass",
    songUrl: "https://soundcloud.com/nightbassrecords/event-horizon-area-code-ft-pvc",
    songTitle: "Event Horizon - Area Code (ft.PVC)",
  },
  {
    id: 991354150,
    channelUrl: "https://soundcloud.com/nightbassrecords",
    channelTitle: "Night Bass",
    songUrl: "https://soundcloud.com/nightbassrecords/event-horizon-intentions",
    songTitle: "Event Horizon - Intentions",
  },
  {
    id: 979662016,
    channelUrl: "https://soundcloud.com/marakirecords/",
    channelTitle: "Maraki Records",
    songUrl: "https://soundcloud.com/marakirecords/event-horizon-papps-cognitive",
    songTitle: "Event Horizon & Papps - Cognitive",
  },
  {
    id: 965001367,
    channelUrl: "https://soundcloud.com/inrotationrecs/",
    channelTitle: "IN / ROTATION",
    songUrl: "https://soundcloud.com/inrotationrecs/event-horizon-shahay-beat",
    songTitle: "Event Horizon & Shahay - Beat Rider",
  },
  {
    id: 832408972,
    channelUrl: "https://soundcloud.com/feuille-vierge/",
    channelTitle: "Feuille Vierge",
    songUrl: "https://soundcloud.com/feuille-vierge/event-horizon-vitamin-d",
    songTitle: "Event Horizon - Vitamin D",
  },
  {
    id: 947367988,
    channelUrl: "https://soundcloud.com/wubclubofficial/",
    channelTitle: "The Wub Club",
    songUrl: "https://soundcloud.com/wubclubofficial/event-horizon-gojira",
    songTitle: "Event Horizon - Gojira",
  },
  {
    id: 936937555,
    channelUrl: "https://soundcloud.com/digital_koala/",
    channelTitle: "Digital Koala",
    songUrl: "https://soundcloud.com/digital_koala/digital-koala-event-horizon-ft-dread-mc-khabib",
    songTitle: "Digital Koala & Event Horizon ft. Dread MC - Khabib",
  },
  {
    id: 918140161,
    channelUrl: "https://soundcloud.com/nightbassrecords/",
    channelTitle: "Night Bass",
    songUrl: "https://soundcloud.com/nightbassrecords/event-horizon-reset",
    songTitle: "Event Horizon - Reset",
  },
  {
    id: 878549452,
    channelUrl: "https://soundcloud.com/strictly-flava/",
    channelTitle: "Strictly Flava",
    songUrl: "https://soundcloud.com/strictly-flava/event-horizon-for-you",
    songTitle: "Event Horizon - For You",
  },
  {
    id: 850200322,
    channelUrl: "https://soundcloud.com/wubclubofficial/",
    channelTitle: "The Wub Club",
    songUrl: "https://soundcloud.com/wubclubofficial/late-night-thoughts",
    songTitle: "Event Horizon - Late Night Thoughts",
  },
  {
    id: 783707113,
    channelUrl: "https://soundcloud.com/crucast/",
    channelTitle: "CRUCAST",
    songUrl: "https://soundcloud.com/crucast/event-horizon-dubplate-1",
    songTitle: "Event Horizon - Dubplate",
  },
  {
    id: 734773084,
    channelUrl: "https://soundcloud.com/supersizeuk/",
    channelTitle: "@SUPERSIZEUK",
    songUrl: "https://soundcloud.com/supersizeuk/event-horizon-fear",
    songTitle: "Event Horizon - Fear",
  },
  {
    id: 707683144,
    channelUrl: "https://soundcloud.com/saucyonline/",
    channelTitle: "Saucy",
    songUrl: "https://soundcloud.com/saucyonline/event-horizon-lucid",
    songTitle: "Event Horizon - Lucid",
  },
  {
    id: 636718236,
    channelUrl: "https://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "https://soundcloud.com/event_horizonmusic/event-horizon-watching-you-1",
    songTitle: "Event Horizon - Watching You",
  },
  {
    id: 617097033,
    channelUrl: "https://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "https://soundcloud.com/event_horizonmusic/event-horizon-the-reaper",
    songTitle: "Event Horizon - The Reaper",
  },
  {
    id: 592579872,
    channelUrl: "https://soundcloud.com/gassedbristol/",
    channelTitle: "Gassed Bass",
    songUrl: "https://soundcloud.com/gassedbristol/event-horizon-scratch-free-download",
    songTitle: "Event Horizon - Scratch",
  },
  {
    id: 556973970,
    channelUrl: "https://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "https://soundcloud.com/event_horizonmusic/event-horizon-the-invasion-2",
    songTitle: "Event Horizon - The Invasion",
  },
  {
    id: 516115878,
    channelUrl: "https://soundcloud.com/openoutlets/",
    channelTitle: "Open Outlets",
    songUrl: "https://soundcloud.com/openoutlets/event-horizon-go",
    songTitle: "Event Horizon - Go",
  },
  {
    id: 501194928,
    channelUrl: "https://soundcloud.com/saucyonline/",
    channelTitle: "Saucy",
    songUrl: "https://soundcloud.com/saucyonline/event-horizon-unseen-forces",
    songTitle: "Event Horizon - Unseen Forces",
  },
  {
    id: 485146269,
    channelUrl: "https://soundcloud.com/brokensyndicate/",
    channelTitle: "BRØKEN",
    songUrl: "https://soundcloud.com/brokensyndicate/bkn038-event-horizon-tenang-ascent",
    songTitle: "Event Horizon - Tenang Ascent",
  },
  {
    id: 448156434,
    channelUrl: "https://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "https://soundcloud.com/event_horizonmusic/event-horizon-rituals",
    songTitle: "Event Horizon - Rituals",
  },
  {
    id: 426655371,
    channelUrl: "https://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "https://soundcloud.com/event_horizonmusic/future-mask-off-event-horizon-remix-vip",
    songTitle: "Future - Mask Off (Event Horizon Remix VIP)",
  },
  {
    id: 406088604,
    channelUrl: "https://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "https://soundcloud.com/event_horizonmusic/event-horizon-x-foundry-abomination-1",
    songTitle: "Event Horizon & Foundry - Abomination",
  },
  {
    id: 389935290,
    channelUrl: "https://soundcloud.com/articulate-sound/",
    channelTitle: "Articulate Sound",
    songUrl: "https://soundcloud.com/articulate-sound/event-horizon-flying-saucers-1",
    songTitle: "Event Horizon - Flying Saucers",
  },
  {
    id: 366337844,
    channelUrl: "https://soundcloud.com/gassedbristol/",
    channelTitle: "Gassed Bass",
    songUrl: "https://soundcloud.com/gassedbristol/event-horizon-doesnt-matter-free-download",
    songTitle: "Event Horizon - Doesn't Matter",
  },
  {
    id: 345927581,
    channelUrl: "https://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "https://soundcloud.com/event_horizonmusic/event-horizon-lockdown-1",
    songTitle: "Event Horizon - Lockdown",
  },
  {
    id: 331371913,
    channelUrl: "https://soundcloud.com/crucast/",
    channelTitle: "CRUCAST",
    songUrl: "https://soundcloud.com/crucast/future-mask-off-event-horizon-remix",
    songTitle: "Future - Mask Off (Event Horizon Remix)",
  },
  {
    id: 327847012,
    channelUrl: "https://soundcloud.com/packlondon/",
    channelTitle: "Pack London",
    songUrl: "https://soundcloud.com/packlondon/event-horizon-voices-free-download",
    songTitle: "Event Horizon - Voices",
  },
  {
    id: 325384914,
    channelUrl: "https://soundcloud.com/projectalloutrecords/",
    channelTitle: "Project Allout Records",
    songUrl: "https://soundcloud.com/projectalloutrecords/event-horizon-wrong-turn-lengerz-3",
    songTitle: "Event Horizon - Wrong Turn",
  },
  {
    id: 324633906,
    channelUrl: "https://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "https://soundcloud.com/event_horizonmusic/event-horizon-skanka-1",
    songTitle: "Event Horizon - Skanka",
  },
  {
    id: 315911875,
    channelUrl: "https://soundcloud.com/3000bass/",
    channelTitle: "3000 BASS",
    songUrl: "https://soundcloud.com/3000bass/event-horizon-kamikaze-free-download",
    songTitle: "Event Horizon - Kamikaze",
  },
  {
    id: 282450092,
    channelUrl: "https://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "https://soundcloud.com/event_horizonmusic/event-horizon-fatter",
    songTitle: "Event Horizon - Fatter",
  },
  {
    id: 272902970,
    channelUrl: "ttps://soundcloud.com/event_horizonmusic/",
    channelTitle: "Event Horizon",
    songUrl: "ttps://soundcloud.com/event_horizonmusic/t2-heartbroken-ftjodie-event-horizon-remix",
    songTitle: "T2 - Heartbroken (ft.Jodie) (Event Horizon Remix)",
  },
];

export default songs;
